#!/bin/bash
#Muutuja küsimine jasalvestamine
echo -e "Sisesta suvaline arv: \c"
read arv
#0 ja 1 eemaldamine
if [ $arv -eq 0 -o $arv -eq 1 ]; then
	echo "$arv ei ole algarv!"
else
#Tsükli seadmine
	kontroll=2
	while [ $(($arv % $kontroll)) -ne 0 ]
	do
		kontroll=$(($kontroll + 1))
	done
#Algarvu kontroll ja teadvustamine
	if [ $arv -eq $kontroll ]; then
		echo "$arv on algav!"
	else
		echo "$arv ei ole algarv!"
	fi
fi
