#!/bin/bash
#Küsimine
echo "Sisestage oma vanus: "
#Salvestamine
read vanus
#Võrdlused
if [ $vanus -gt 0 -a $vanus -lt 11 ]; then
	echo "Oled laps"
elif [ $vanus -ge 11 -a $vanus -lt 18 ]; then
	echo "Oled nooruk"
elif [ $vanus -ge 18 -a $vanus -lt 63 ]; then
	echo "Oled täiskasvanu"
elif [ $vanus -ge 63 ]; then
	echo "Oled seenior"
else
	echo "Viga sisendis"
fi
