#!/bin/bash
#Väärtuse küsimine
echo -e "Sisesta tunni väärtus: \c"
read aeg
#Võrdlemine
if [ $aeg -ge 6 -a $aeg -le 12 ]; then
	echo "Tere hommikut!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere päevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere õhtust!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head ööd!"
else
	echo "Vale sisend"
fi
